name: Develop workflow

on:
  # Запуск при любом pull-request в ветку backend
  pull_request:
    branches: [ backend ]
  # Запуск при любом push-действии в ветку backend
  push:
    branches: [ backend-feat-workflow-message-fix ]

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checking out a repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        # Устанавливаем Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'



  send_message:
    runs-on: ubuntu-latest
    needs: tests
    # Выполнять только при успешном выполнении предыдущих задач
    if: ${{ success() }}
    steps:
      # Получение активной ветки
      - name: Get branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      # Получение активного коммита
      - name: Get commit SHA
        run: echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      # Отправка сообщения в канал https://t.me/itm_project_actions
      - name: Send message to Telegram Channel "ITM-project actions"
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Разработчик ${{ github.actor }} успешно выполнил ${{ github.workflow }}!
            Ветка: ${{ env.BRANCH_NAME }}
            Тип операции: ${{ github.event_name }} ${{ github.event.pull_request.base.ref }}
            Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ env.COMMIT_SHA }}
